### ISSUE TITLE
Outdated Styleline extension settings for VS Code

### ISSUE THREAD

**Issue by lykoffant** [YaroslavWeb/react-third-hand#2]
**Describe the bug**

These configuration parameters are no longer relevant (`.vscode/settings.json`):

```json
{
  "stylelint.useLocal": true,
  "stylelint.autoFixOnSave": true
}
```

> There are no `stylelint.useLocal` and `stylelint.autoFixOnSave` parameters in the current Stylelint extension documentation.

**Possible solution**

This parameter is relevant for auto-formatting styles (`.vscode/settings.json`):

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.stylelint": true
  }
}
```

> The Stylelint extension uses a configuration from local user files by default. Therefore, the `stylelint.useLocal` parameter may have been removed.

**Environment:**

- IDE: **VS Code v1.73.1**
- Extension for VS Code: **Stylelint v1.2.3** _(stylelint.vscode-stylelint)_

**Comment by YaroslavWeb** [comment]
I used these settings for the stylelint-plus plugin _(hex-ci.stylelint-plus)_. 

I will remove these settings from the **settings.json** file
